### ISSUE TITLE
tacker installation issue 

### ISSUE THREAD

**Issue by SaltySooda** [free5gmano/tacker-example-plugin#14]
when we run this command  "openstack vim register --config-file vim_config.yaml --description 'free5gc vim' --is-default free5gc".
it shows "public endpoint for nfv-orchestration service not found".
before that, we follow every step exactly.but it seems we did not install tacker successfully.
what happend?

**Comment by TitanLi** [comment]
Feeling maybe vim_config.yaml not set parameters complete the file needs to be updated to conform to the environment
You can test command "openstack vnf list" to see if Tacker is successfully installed

**Comment by SaltySooda** [comment]
stack@user:~$ openstack vnf list
openstack: 'vnf list' is not an openstack command.

**Comment by TitanLi** [comment]
It seems that you did not install successfully Tacker
We tested without problems
You can refer to https://docs.openstack.org/tacker/latest/ to install Tacker
